<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>draft.dev</groupId>
    <artifactId>mailgun-analytics-demo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>1. Configuring and Using The Mailgun Logs API</module>
        <module>1. Configuring and Using The Mailgun Logs API/1.1 Simple Log Demo</module>
        <module>1. Configuring and Using The Mailgun Logs API/1.3 Using a Filter Object</module>
        <module>1. Configuring and Using The Mailgun Logs API/1.4 Paginating Log Results</module>
        <module>2. Pulling Suppression Data</module>
        <module>3. Working with Stats and Tags</module>
        <module>4. Creating a log file</module>
        <module>4. Creating a log file/4.1 JSON Log File Serialization</module>
    </modules>

    <properties>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Source: https://mvnrepository.com/artifact/com.mailgun/mailgun-java -->
        <dependency>
            <groupId>com.mailgun</groupId>
            <artifactId>mailgun-java</artifactId>
            <version>2.4.1</version>
        </dependency>
    </dependencies>

</project>